"""What the feedback table holds, and whether anybody wrote down what it caused.

WHY THIS EXISTS, AND WHY IT IS NOT AN UNREAD FLAG

Three of Michelle's four Investor Report asks were built. The code quotes
her words back. And none of it reached HANDOFF, so every list assembled
from HANDOFF was missing them for two weeks -- including one that went
into a prompt and came back as established fact.

**An unread flag would have fired, been cleared by the reading that
already happened, and changed nothing.** The failure was not looking; it
was that looking left no trace. So this asks a different question:

    has anybody written down what this row caused?

A row is CLAIMED when something in the repo cites it by id. Not by
opening a page -- by writing a sentence somewhere a person will find it.

THE CONVENTION, WHICH IS ONE STRING

Write `feedback #3` anywhere in the repo: a code comment, a test
docstring, a HANDOFF entry, a design doc. That is the whole ceremony. It
is greppable, it survives a rename, and it costs less than the sentence
it sits inside.

A row with nothing to do is claimed the same way -- `feedback #1 -- no
ask` -- because "there was nothing here" is a judgement somebody made and
is worth exactly as much as any other. The alternative was a heuristic
that reads the message and guesses whether it contains a request, which
would be wrong about a short one-line ask and would make the digest lie
in the direction of silence.

GENERATED WHOLESALE, NEVER HAND-EDITED

`render()` returns a block; `write_into()` replaces everything between
the markers in a file with it. A maintained list becomes a fourth source
of truth and goes stale exactly the way the branch table did -- so this
one is regenerated, and the marker is the seam that makes replacing it
safe.
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Any, Iterable

BEGIN = "<!-- FEEDBACK:BEGIN -- generated by tools/feedback_digest.py, do not edit -->"
END = "<!-- FEEDBACK:END -->"

# Where a citation may live. Templates and Python and markdown, which is
# every place a person writes prose in this repo.
CITE_GLOBS = ("*.py", "*.md", "templates/**/*.html", "docs/*.md")

# `feedback #3`, `feedback row 3`, `feedback-3`. Deliberately loose about
# the separator and deliberately strict about the word: a bare "#3" would
# match an issue number, a heading anchor and a hex colour.
CITE = re.compile(r"feedback[\s#-]*(?:row[\s#-]*)?#?\s*(\d+)", re.IGNORECASE)


def rows(db_path: Path | str | None = None) -> list[dict[str, Any]]:
    """Every feedback row, oldest first."""
    from tools import feedback_db

    path = Path(db_path) if db_path else feedback_db.get_db_path()
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        return [dict(r) for r in conn.execute(
            "SELECT id, tool, message, page_url, created_at "
            "FROM feedback ORDER BY id")]
    finally:
        conn.close()


def citations(root: Path | str = ".") -> dict[int, list[str]]:
    """row id -> the files that cite it.

    THE FILES THAT ARE ABOUT CITATIONS DO NOT COUNT, and there are
    exactly two: this module and its test. The generated block would
    otherwise cite every row it lists, and the test's fixtures --
    "feedback #2 done", "feedback row 3" -- would claim real production
    rows on behalf of nobody. A checker satisfied by its own examples is
    the dead-reader defect in a new costume.

    A test that is about the WORK still counts, and should:
    `test_investor_notes` carries *"Her word for it, from feedback row
    3"*, which is a person saying why that test exists.
    """
    root = Path(root)
    seen: dict[int, list[str]] = {}
    for pattern in CITE_GLOBS:
        for path in sorted(root.glob(pattern)) + sorted(root.glob("**/" + pattern)):
            if not path.is_file() or ".git" in path.parts:
                continue
            if path.name in ("feedback_digest.py", "test_feedback_digest.py"):
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            body = text
            if BEGIN in text and END in text:
                body = text[:text.index(BEGIN)] + text[text.index(END):]
            for match in CITE.finditer(body):
                rid = int(match.group(1))
                name = str(path.relative_to(root)).replace("\\", "/")
                if name not in seen.setdefault(rid, []):
                    seen[rid].append(name)
    return seen


def _first_line(message: str | None) -> str:
    for line in (message or "").splitlines():
        line = line.strip()
        if line:
            return line[:90] + ("…" if len(line) > 90 else "")
    return "(empty)"


def _count_items(message: str | None) -> int:
    """Numbered items, reported rather than interpreted. Zero is not
    "nothing to do" -- it is "not written as a list"."""
    return len(re.findall(r"^\s*\d+[.)]", message or "", re.MULTILINE))


def render(feedback: Iterable[dict[str, Any]],
           cited: dict[int, list[str]]) -> str:
    """The block. Deterministic given its inputs, so a regeneration that
    changes nothing produces byte-identical output."""
    feedback = list(feedback)
    unclaimed = [r for r in feedback if not cited.get(int(r["id"]))]
    lines = [
        BEGIN,
        "",
        f"**{len(feedback)} rows. {len(unclaimed)} unclaimed.** A row is "
        f"claimed when something in the repo cites it — write "
        f"`feedback #N` in a comment, a test, or here. A row with nothing "
        f"to do is claimed the same way: say so and cite it.",
        "",
        "| # | when | tool | first line | items | claimed by |",
        "|---|---|---|---|---|---|",
    ]
    for r in feedback:
        rid = int(r["id"])
        where = cited.get(rid) or []
        items = _count_items(r.get("message"))
        lines.append(
            "| **%d** | %s | %s | %s | %s | %s |" % (
                rid,
                (r.get("created_at") or "")[:10],
                r.get("tool") or "—",
                _first_line(r.get("message")).replace("|", "\\|"),
                items or "—",
                ", ".join(f"`{w}`" for w in where) if where
                else "**UNCLAIMED**"))
    lines += ["", END]
    return "\n".join(lines)


def write_into(path: Path | str, block: str) -> bool:
    """Replace the marked region. Returns True when the file changed.

    Refuses rather than guesses when the markers are missing: appending
    to the end of a 4,000-line document is how a generated section ends
    up in two places, each half right.
    """
    path = Path(path)
    text = path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise ValueError(
            f"{path} has no FEEDBACK:BEGIN/END markers. Add them where the "
            f"block should live; this will not choose a place for you.")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + block + tail
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


if __name__ == "__main__":  # pragma: no cover - operator entry point
    import sys

    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    block = render(rows(), citations(root))
    print(block)
